#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
#    username: hyun
#    password: hyun45183

# server : 내용 비워두면
# port : 8080
# context-path : /    와 같음

server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: hyun
    password: hyun45183
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update    # 처음에 create, 나중 update / create로 놔두면 계속 drop하고 새로 생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # DB에 그대로   # SpringPhysicalNamingStrategy 사용시 createDate -> create_date
      use-new-id-generator-mappings: false    # jpa에서 사용하는 기본 넘버링 전략을 따라가지 않음
    show-sql: true  # 콘솔창에 보임
    properties:
      hibernate.format_sql: true  # 콘솔창에 한줄씩 나타남

  jackson:
    serialization:
      fail-on-empty-beans: false